name: Autograding Tests
on: [push, repository_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r exercicio-tdd/requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest exercicio-tdd/