name: Autograding Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  
  repository_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-subtests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Pytest
      id: pytest
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 10
        setup-command: ''

    - name: Autograding Reporter
      if: always()  
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTEST_RESULTS: "${{steps.pytest.outputs.result}}"
      with:
        runners: pytest